name: Build with pip cache being saved between runs

on:
  push:

jobs:

  tests:
    name: Build the charm
    runs-on: ubuntu-20.04
    env:
      PIP_CACHE_DIR: /home/runner/.cache/pip
      CRAFT_SHARED_CACHE: /home/runner/.cache/pip

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: echo to see if variables exist
      run: |
        echo PIP_CACHE_DIR: $PIP_CACHE_DIR
        echo CRAFT_SHARED_CACHE: $CRAFT_SHARED_CACHE
        echo ---
        bash test-env-vars.sh

    - name: echo to see if variables exist (control)
      run: |
        echo PIP_CACHE_DIR: $PIP_CACHE_DIR
        echo CRAFT_SHARED_CACHE: $CRAFT_SHARED_CACHE
        echo ---
        bash test-env-vars.sh
      env:
        PIP_CACHE_DIR: XXX
        CRAFT_SHARED_CACHE: YYY

    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies
    
    - name: emit pip cache directory
      run: pip cache dir

    - uses: canonical/setup-lxd@main
      with:
        channel: latest/stable

    - name: install charmcraft
      run: |
        sudo snap install charmcraft --classic

    - name: emit pip cache directory contents (1)
      run: |
        find $CRAFT_SHARED_CACHE | wc -l
        find $CRAFT_SHARED_CACHE/wheels | wc -l

    - name: pip install something to show we can cache things
      run: |
        pip install fastapi --no-binary :all:

    - name: emit pip cache directory contents (1b)
      run: |
        find $CRAFT_SHARED_CACHE | wc -l
        find $CRAFT_SHARED_CACHE/wheels | wc -l

    - name: emit charmcraft's default pip cache
      run: |
        ls -la /home/runner/snap/charmcraft/common/cache/charmcraft/ || true
        ls -la /home/runner/snap/charmcraft/common/cache/charmcraft/charmcraft-buildd-base-v8.0/ || true
        ls -la /home/runner/snap/charmcraft/common/cache/charmcraft/charmcraft-buildd-base-v8.0/*/pip || true
        find /home/runner/snap/charmcraft/common/cache/charmcraft/charmcraft-buildd-base-v8.0/*/pip | wc -l || true
        find /home/runner/snap/charmcraft/common/cache/charmcraft/charmcraft-buildd-base-v8.0/*/pip/wheels | wc -l || true

    - name: pack charm from scratch
      run: |
        charmcraft clean --verbosity debug # to be sure
        time charmcraft pack --verbosity debug

    - name: emit charmcraft's default pip cache (after)
      run: |
        ls -la /home/runner/snap/charmcraft/common/cache/charmcraft/ || true
        ls -la /home/runner/snap/charmcraft/common/cache/charmcraft/charmcraft-buildd-base-v8.0/ || true
        ls -la /home/runner/snap/charmcraft/common/cache/charmcraft/charmcraft-buildd-base-v8.0/*/pip || true
        find /home/runner/snap/charmcraft/common/cache/charmcraft/charmcraft-buildd-base-v8.0/*/pip | wc -l || true
        find /home/runner/snap/charmcraft/common/cache/charmcraft/charmcraft-buildd-base-v8.0/*/pip/wheels | wc -l || true

    - name: emit pip cache directory contents (2)
      run: |
        find $PIP_CACHE_DIR | wc -l
        find $PIP_CACHE_DIR/wheels | wc -l

    - name: pack charm from reused container
      run: |
        # charmcraft clean --verbosity debug # to be sure
        time charmcraft pack --verbosity debug

    - name: emit pip cache directory contents (3)
      run: |
        find $PIP_CACHE_DIR | wc -l
        find $PIP_CACHE_DIR/wheels | wc -l

    - name: pack charm from new container with pip cache
      run: |
        charmcraft clean --verbosity debug # to be sure
        time charmcraft pack --verbosity debug

    - name: emit pip cache directory contents (4)
      run: |
        find $PIP_CACHE_DIR | wc -l
        find $PIP_CACHE_DIR/wheels | wc -l

    - run: ls -l /home/runner/.cache
    - run: ls -l $PIP_CACHE_DIR

