name: Build without pip cache configured

on:
  push:

jobs:

  tests:
    name: Build the charm
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies
    
    - uses: canonical/setup-lxd

    - name: install charmcraft
      run: |
        sudo snap install charmcraft --classic

    - name: emit pip cache directory contents (1)
      run: |
        find /home/scribs/.cache/pip | wc -l
        find /home/scribs/.cache/pip/wheels | wc -l

    - name: pack charm from scratch
      run: |
        charmcraft clean --verbosity debug # to be sure
        time charmcraft pack --verbosity debug

    - name: emit pip cache directory contents (2)
      run: |
        find /home/scribs/.cache/pip | wc -l
        find /home/scribs/.cache/pip/wheels | wc -l

    - name: pack charm from reused container
      run: |
        # charmcraft clean --verbosity debug # to be sure
        time charmcraft pack --verbosity debug

    - name: emit pip cache directory contents (3)
      run: |
        find /home/scribs/.cache/pip | wc -l
        find /home/scribs/.cache/pip/wheels | wc -l

    - name: pack charm from new container with pip cache
      run: |
        charmcraft clean --verbosity debug # to be sure
        time charmcraft pack --verbosity debug

    - name: emit pip cache directory contents (4)
      run: |
        find /home/scribs/.cache/pip | wc -l
        find /home/scribs/.cache/pip/wheels | wc -l

