name: Test what happens if you do setup-python with cache=pip, and install nothing

on:
  push:

jobs:

  tests:
    name: test setup-python pip cache
    runs-on: ubuntu-20.04

    steps:
    # (required for setup-python action)
    - name: create an empty requirements.txt
      run: touch requirements.txt

    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies

    - run: ls -l /home/runner/.cache
