name: Test what happens if you do setup-python with cache=pip, and install nothing

on:
  push:

jobs:

  tests:
    name: test setup-python pip cache
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies

    - run: ls -l /home/runner/.cache
